# Generated by Django 4.2.7 on 2024-01-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='ghost', max_length=50, null=True, verbose_name='Username'),
        ),
    ]
