# Generated by Django 4.2.7 on 2024-01-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('comment', models.TextField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='MailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=100)),
                ('send_time', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('created', 'Created'), ('launched', 'Launched')], default='created', max_length=10)),
                ('client_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client')),
            ],
            options={
                'verbose_name': 'mail campaign',
                'verbose_name_plural': 'mail campaigns',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'template',
                'verbose_name_plural': 'templates',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=100)),
                ('attempt_datetime', models.DateTimeField()),
                ('completion_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('launched', 'Launched'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=10)),
                ('server_response', models.TextField(blank=True, null=True)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing', to='main.mailcampaign')),
            ],
            options={
                'verbose_name': 'mailing log',
                'verbose_name_plural': 'mailing logs',
                'ordering': ['-attempt_datetime'],
            },
        ),
        migrations.AddField(
            model_name='mailcampaign',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailingmessage'),
        ),
    ]
