# Generated by Django 4.2.7 on 2024-01-28 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mailinglog_options_client_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailcampaign',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.mailingmessage'),
            preserve_default=False,
        ),
    ]
