# Generated by Django 4.2.7 on 2024-01-18 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_tag_mailingmessage_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mail_campaign',
        ),
        migrations.RemoveField(
            model_name='mailingmessage',
            name='mail_campaign',
        ),
        migrations.AddField(
            model_name='mailcampaign',
            name='client_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client'),
        ),
        migrations.AddField(
            model_name='mailcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mailingmessage'),
        ),
    ]
