# Generated by Django 4.2.7 on 2024-01-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_client_mail_campaign_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['tag'], 'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
        migrations.AlterModelOptions(
            name='mailcampaign',
            options={'ordering': ['send_time'], 'verbose_name': 'mail campaign', 'verbose_name_plural': 'mail campaigns'},
        ),
        migrations.AddField(
            model_name='mailcampaign',
            name='campaign_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='mailcampaign',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailcampaign',
            name='send_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
