# Generated by Django 4.2.7 on 2024-01-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_client_options_alter_mailcampaign_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailcampaign',
            name='campaign_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mailcampaign',
            name='send_time',
            field=models.DateTimeField(blank=True, default='-', null=True),
        ),
    ]
