# Generated by Django 4.2.7 on 2024-01-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mailcampaign_campaign_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailcampaign',
            name='send_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
