# Generated by Django 4.2.7 on 2024-01-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_mailcampaign_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailcampaign',
            name='time_completed',
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='completion_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='status',
            field=models.CharField(choices=[('launched', 'Launched'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=10),
        ),
    ]
