# Generated by Django 4.2.7 on 2024-01-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_mailcampaign_time_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='campaign_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='server_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
